//AUTH
export const IS_AUTH = 'IS_AUTH'
export const GET_LOGIN_PAGE = 'GET_LOGIN_PAGE'

//PRODUCT PAGE TYPES
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const ADD_CATEGORIES = 'ADD_CATEGORIES'
export const GET_PRODUCTS_LENGTH = 'GET_PRODUCTS_LENGTH'
export const PANEL_OPEN_CLOSE = 'PANEL_OPEN_CLOSE'
export const GET_PRODUCTS_CATEGORIES = 'GET_PRODUCTS_CATEGORIES'
export const IS_LOADING = 'IS_LOADING'
export const ADD_LOADING ='ADD_LOADING'
export const GET_PRODUCTS_ALL ='GET_PRODUCTS_ALL'

//PROFILE
export const GET_USER_INFO = 'GET_USER_INFO'
export const GET_USER_BASKET = 'GET_USER_BASKET'
export const ADD_REMOVE_USER_BASKET = 'ADD_REMOVE_USER_BASKET'
export const GET_OWN_PRODUCTS = 'GET_OWN_PRODUCTS'
export const ADD_OWN_PRODUCTS = 'ADD_OWN_PRODUCTS'
export const GET_ORDER_PRODUCTS = 'GET_ORDER_PRODUCTS'
export const CLOSE_PRODUCT_PANEL = 'CLOSE_PRODUCT_PANEL'
export const GET_BLOGS = 'GET_BLOGS'
export const ADD_BLOGS = 'ADD_BLOGS'

