//PRODUCT PAGE TYPES
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_PRODUCTS_LENGTH = 'GET_PRODUCTS_LENGTH'
export const PANEL_OPEN_CLOSE = 'PANEL_OPEN_CLOSE'
export const GET_PRODUCTS_CATEGORIES = 'GET_PRODUCTS_CATEGORIES'
export const IS_LOADING = 'IS_LOADING'
//AUTH
export const IS_AUTH = 'IS_AUTH'
export const GET_LOGIN_PAGE = 'GET_LOGIN_PAGE'

//PROFILE
export const GET_USER_INFO = 'GET_USER_INFO'
export const GET_USER_BASKET = 'GET_USER_BASKET'
export const GET_OWN_PRODUCTS = 'GET_OWN_PRODUCTS'